---
- name: Place the init script
  template:
    src: "sahara-upstart-init.j2"
    dest: "/etc/init/{{ program_name }}.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  notify:
    - Restart sahara services
  tags:
    - upstart-init
    - sahara-init

- name: Reload init scripts
  shell: |
    initctl reload-configuration
  notify:
    - Restart sahara services
  tags:
    - upstart-init
    - sahara-init

- name: Load service
  service:
   name: "{{ program_name }}"
   enabled: "yes"
  notify:
    - Restart sahara services
  tags:
    - upstart-init
    - sahara-init
